# Generated by Django 4.1 on 2022-08-30 08:49

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('todo', '0001_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='toodo',
            name='date',
            field=models.DateTimeField(auto_now_add=True),
        ),
    ]
