# Generated by Django 4.1 on 2022-08-30 08:52

from django.db import migrations, models
import django.utils.timezone


class Migration(migrations.Migration):

    dependencies = [
        ('todo', '0002_alter_toodo_date'),
    ]

    operations = [
        migrations.AlterField(
            model_name='toodo',
            name='date',
            field=models.DateTimeField(default=django.utils.timezone.now),
        ),
    ]
